services:
  uzchess-backend:
    build: .
    command: >
      sh -c "npm run migrate && node dist/main.js"
    env_file:
      - .env
    ports:
      - "8888:8888"
    restart: always
    container_name: uzchess
    networks:
      - uzchess
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads/
  db:
    image: postgres:18-alpine
    env_file:
      - .env
    container_name: postgress-db
    networks:
      - uzchess
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - uzchess:/var/lib/postgresql/data

volumes:
  uzchess:
  uploads:

networks:
  uzchess:
    driver: bridge


