import { MigrationInterface, QueryRunner } from "typeorm";

export class Uzchess1775882801585 implements MigrationInterface {
    name = 'Uzchess1775882801585'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "reportCategories" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "title" character varying(64) NOT NULL, "order" integer, CONSTRAINT "UQ_ac74492c6fc090dbdb3d8051909" UNIQUE ("title"), CONSTRAINT "PK_0d1e145a1234417e2c77eba879b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."otpCodes_type_enum" AS ENUM('register', 'passwordReset', 'numberChange', 'emailChange')`);
        await queryRunner.query(`CREATE TABLE "otpCodes" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "code" character varying(6) NOT NULL, "type" "public"."otpCodes_type_enum" NOT NULL, CONSTRAINT "PK_98754524ec2e0c9a0b5f3874e04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "languages" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "title" character varying(32) NOT NULL, "code" character varying(2) NOT NULL, CONSTRAINT "UQ_06df62e773ec68318919dafacf7" UNIQUE ("title"), CONSTRAINT "UQ_7397752718d1c9eb873722ec9b2" UNIQUE ("code"), CONSTRAINT "PK_b517f827ca496b29f4d549c631d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "difficulties" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "title" character varying(32) NOT NULL, "icon" character varying(128) NOT NULL, CONSTRAINT "UQ_de991ed11f2258b97640f71a45a" UNIQUE ("title"), CONSTRAINT "PK_4c3dd46c9ed9b426d0307e45b3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usersLessons" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "courseLessonId" integer NOT NULL, "stoppedAt" integer, "isCompleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f4f07b7e07f32bf02597fa2def8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courseLessons" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "courseId" integer NOT NULL, "courseSectionId" integer NOT NULL, "title" character varying(128) NOT NULL, "content" text, "thumbnail" character varying(128), "video" character varying(256) NOT NULL, "order" integer, "isFree" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_0025dab46496f8dfa677939c773" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courseSections" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "courseId" integer NOT NULL, "title" character varying(256) NOT NULL, "order" integer, "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_cf394f0c7ed24362f151d407c25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courseReviews" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "courseId" integer NOT NULL, "rating" integer NOT NULL, "comment" character varying(512), CONSTRAINT "PK_4ed7d8bd064b45160cac33cdf97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courseLikes" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "courseId" integer NOT NULL, CONSTRAINT "PK_ae1449fc860ab66f70c34f845f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courseCategories" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "title" character varying(64) NOT NULL, CONSTRAINT "UQ_c1d6cc8527caa216a8313fe03bc" UNIQUE ("title"), CONSTRAINT "PK_6abac9e602f9ddbe55a5876d8ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coursePurchases" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "courseId" integer NOT NULL, "isCompleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_81d34ae23c9501694ab062cbd24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "authorId" integer NOT NULL, "categoryId" integer NOT NULL, "languageId" integer NOT NULL, "difficultyId" integer NOT NULL, "title" character varying(128) NOT NULL, "image" character varying(128) NOT NULL, "price" numeric(12,2) NOT NULL, "newPrice" numeric(12,2), "reviewsCount" integer NOT NULL DEFAULT '0', "rating" numeric(2,1), "sectionsCount" integer NOT NULL DEFAULT '0', "lessonsCount" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "authors" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "fullName" character varying(64) NOT NULL, CONSTRAINT "PK_d2ed02fabd9b52847ccb85e6b88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bookCategories" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "title" character varying(64) NOT NULL, CONSTRAINT "UQ_2556e7db3ce3525a0104f73e94b" UNIQUE ("title"), CONSTRAINT "PK_ea689f47d8e96f5545bcdb411b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bookLikes" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "bookId" integer NOT NULL, CONSTRAINT "PK_9018b62069141f395e0d99c65bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "books" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "authorId" integer NOT NULL, "categoryId" integer NOT NULL, "languageId" integer NOT NULL, "difficultyId" integer NOT NULL, "title" character varying(128) NOT NULL, "image" character varying(128), "description" text NOT NULL, "price" numeric(12,2) NOT NULL, "newPrice" numeric(12,2), "rating" numeric(2,1), "reviewsCount" integer NOT NULL DEFAULT '0', "pages" integer NOT NULL, "pubDate" date NOT NULL, CONSTRAINT "PK_f3f2f25a099d24e12545b70b022" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bookReviews" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "bookId" integer NOT NULL, "rating" integer NOT NULL, "comment" character varying(512), CONSTRAINT "PK_fbd29f7d604cf4ba60c0f28a384" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin', 'superAdmin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_logintype_enum" AS ENUM('email', 'number')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "fullName" character varying(64) NOT NULL, "profileImage" character varying(128), "login" character varying(64) NOT NULL, "loginType" "public"."users_logintype_enum" NOT NULL, "password" character varying(128), "birthDate" date, "isVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_2d443082eccd5198f95f2a36e2c" UNIQUE ("login"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reports_target_enum" AS ENUM('book', 'course')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "categoryId" integer NOT NULL, "target" "public"."reports_target_enum" NOT NULL, "targetId" integer NOT NULL, "description" character varying(256), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "title" character varying(256) NOT NULL, "image" character varying(128) NOT NULL, "content" text NOT NULL, "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_39a43dfcb6007180f04aff2357e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "newsViews" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "newsId" integer NOT NULL, "firstDate" TIMESTAMP NOT NULL DEFAULT now(), "lastDate" TIMESTAMP NOT NULL, "count" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_f6ac59626e056de73693dfb90c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "countries" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "title" character varying(64) NOT NULL, "flag" character varying(128) NOT NULL, CONSTRAINT "UQ_f0ab39b0865e4939e37308fe0a7" UNIQUE ("title"), CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."matches_type_enum" AS ENUM('classic', 'rapid', 'blitz')`);
        await queryRunner.query(`CREATE TYPE "public"."matches_winner_enum" AS ENUM('first', 'second', 'draw')`);
        await queryRunner.query(`CREATE TABLE "matches" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "firstPlayerId" integer NOT NULL, "firstPlayerResult" integer NOT NULL, "secondPlayerId" integer NOT NULL, "secondPlayerResult" integer NOT NULL, "type" "public"."matches_type_enum" NOT NULL, "moves" integer NOT NULL, "date" TIMESTAMP NOT NULL, "winner" "public"."matches_winner_enum" NOT NULL, CONSTRAINT "PK_8a22c7b2e0828988d51256117f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "players" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "countryId" integer NOT NULL, "fullName" character varying(64) NOT NULL, "image" character varying(128), "classic" integer, "rapid" integer, "blitz" integer, CONSTRAINT "PK_de22b8fdeee0c33ab55ae71da3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "terms" ("id" SERIAL NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP DEFAULT now(), "content" text NOT NULL, CONSTRAINT "PK_33b6fe77d6ace7ff43cc8a65958" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "otpCodes" ADD CONSTRAINT "FK_43c19e5364178359d22f011805b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usersLessons" ADD CONSTRAINT "FK_6f24d6757ddd06ba077aa50b228" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usersLessons" ADD CONSTRAINT "FK_28d2b83c061b1a449b47c9affca" FOREIGN KEY ("courseLessonId") REFERENCES "courseLessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courseLessons" ADD CONSTRAINT "FK_5db8e75063474458807838819ee" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courseLessons" ADD CONSTRAINT "FK_a5c60b4601e11002e4b92822aee" FOREIGN KEY ("courseSectionId") REFERENCES "courseSections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courseSections" ADD CONSTRAINT "FK_072cc75af9f1b86ecac5a54fb85" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courseReviews" ADD CONSTRAINT "FK_a5d8af87d987287e99993e80dcd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courseReviews" ADD CONSTRAINT "FK_688f4cee5d9de862f4d8196aa2a" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courseLikes" ADD CONSTRAINT "FK_6216bf22d755d4908eb0ff211a3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courseLikes" ADD CONSTRAINT "FK_833e6e71d3c4b3e4ca683bd66ac" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coursePurchases" ADD CONSTRAINT "FK_d970091ff600587ffedd7086e67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coursePurchases" ADD CONSTRAINT "FK_37b463e56d173c75987648c6911" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_fffcbc92f4e8fa650d08be6903d" FOREIGN KEY ("authorId") REFERENCES "authors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_c730473dfb837b3e62057cd9447" FOREIGN KEY ("categoryId") REFERENCES "courseCategories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_a09de3e6027500ac44609a8055f" FOREIGN KEY ("languageId") REFERENCES "languages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_87136dee8b3b8d5ca093961c5e5" FOREIGN KEY ("difficultyId") REFERENCES "difficulties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookLikes" ADD CONSTRAINT "FK_d560de2df6bdb26cc79d3178627" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookLikes" ADD CONSTRAINT "FK_7877622a4f3d062c6811bae00cd" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_54f49efe2dd4d2850e736e9ab86" FOREIGN KEY ("authorId") REFERENCES "authors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_a0f13454de3df36e337e01dbd55" FOREIGN KEY ("categoryId") REFERENCES "bookCategories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_49060974a6295b7f70ac2c102b5" FOREIGN KEY ("languageId") REFERENCES "languages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_78f9d0c7bf6c0588b6d06fd1aef" FOREIGN KEY ("difficultyId") REFERENCES "difficulties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookReviews" ADD CONSTRAINT "FK_362ae32a4a1728e8376e3de429f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookReviews" ADD CONSTRAINT "FK_ca9aae9f8655c98c8a89a7a523a" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_bed415cd29716cd707e9cb3c09c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_7470a830c3002e44860c6aac32c" FOREIGN KEY ("categoryId") REFERENCES "reportCategories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsViews" ADD CONSTRAINT "FK_e43060ca20c8b60cbd24845b41d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsViews" ADD CONSTRAINT "FK_b7f18df25cfb2890f69d18a9ead" FOREIGN KEY ("newsId") REFERENCES "news"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_e990a00c3c12319eb36c7934e73" FOREIGN KEY ("firstPlayerId") REFERENCES "players"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_ed7fcddfe397bd87b90ed29480c" FOREIGN KEY ("secondPlayerId") REFERENCES "players"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_7d976e6c0eaf82fee3975d8e98a" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_7d976e6c0eaf82fee3975d8e98a"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_ed7fcddfe397bd87b90ed29480c"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_e990a00c3c12319eb36c7934e73"`);
        await queryRunner.query(`ALTER TABLE "newsViews" DROP CONSTRAINT "FK_b7f18df25cfb2890f69d18a9ead"`);
        await queryRunner.query(`ALTER TABLE "newsViews" DROP CONSTRAINT "FK_e43060ca20c8b60cbd24845b41d"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_7470a830c3002e44860c6aac32c"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_bed415cd29716cd707e9cb3c09c"`);
        await queryRunner.query(`ALTER TABLE "bookReviews" DROP CONSTRAINT "FK_ca9aae9f8655c98c8a89a7a523a"`);
        await queryRunner.query(`ALTER TABLE "bookReviews" DROP CONSTRAINT "FK_362ae32a4a1728e8376e3de429f"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_78f9d0c7bf6c0588b6d06fd1aef"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_49060974a6295b7f70ac2c102b5"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_a0f13454de3df36e337e01dbd55"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_54f49efe2dd4d2850e736e9ab86"`);
        await queryRunner.query(`ALTER TABLE "bookLikes" DROP CONSTRAINT "FK_7877622a4f3d062c6811bae00cd"`);
        await queryRunner.query(`ALTER TABLE "bookLikes" DROP CONSTRAINT "FK_d560de2df6bdb26cc79d3178627"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_87136dee8b3b8d5ca093961c5e5"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_a09de3e6027500ac44609a8055f"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_c730473dfb837b3e62057cd9447"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_fffcbc92f4e8fa650d08be6903d"`);
        await queryRunner.query(`ALTER TABLE "coursePurchases" DROP CONSTRAINT "FK_37b463e56d173c75987648c6911"`);
        await queryRunner.query(`ALTER TABLE "coursePurchases" DROP CONSTRAINT "FK_d970091ff600587ffedd7086e67"`);
        await queryRunner.query(`ALTER TABLE "courseLikes" DROP CONSTRAINT "FK_833e6e71d3c4b3e4ca683bd66ac"`);
        await queryRunner.query(`ALTER TABLE "courseLikes" DROP CONSTRAINT "FK_6216bf22d755d4908eb0ff211a3"`);
        await queryRunner.query(`ALTER TABLE "courseReviews" DROP CONSTRAINT "FK_688f4cee5d9de862f4d8196aa2a"`);
        await queryRunner.query(`ALTER TABLE "courseReviews" DROP CONSTRAINT "FK_a5d8af87d987287e99993e80dcd"`);
        await queryRunner.query(`ALTER TABLE "courseSections" DROP CONSTRAINT "FK_072cc75af9f1b86ecac5a54fb85"`);
        await queryRunner.query(`ALTER TABLE "courseLessons" DROP CONSTRAINT "FK_a5c60b4601e11002e4b92822aee"`);
        await queryRunner.query(`ALTER TABLE "courseLessons" DROP CONSTRAINT "FK_5db8e75063474458807838819ee"`);
        await queryRunner.query(`ALTER TABLE "usersLessons" DROP CONSTRAINT "FK_28d2b83c061b1a449b47c9affca"`);
        await queryRunner.query(`ALTER TABLE "usersLessons" DROP CONSTRAINT "FK_6f24d6757ddd06ba077aa50b228"`);
        await queryRunner.query(`ALTER TABLE "otpCodes" DROP CONSTRAINT "FK_43c19e5364178359d22f011805b"`);
        await queryRunner.query(`DROP TABLE "terms"`);
        await queryRunner.query(`DROP TABLE "players"`);
        await queryRunner.query(`DROP TABLE "matches"`);
        await queryRunner.query(`DROP TYPE "public"."matches_winner_enum"`);
        await queryRunner.query(`DROP TYPE "public"."matches_type_enum"`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP TABLE "newsViews"`);
        await queryRunner.query(`DROP TABLE "news"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_target_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_logintype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "bookReviews"`);
        await queryRunner.query(`DROP TABLE "books"`);
        await queryRunner.query(`DROP TABLE "bookLikes"`);
        await queryRunner.query(`DROP TABLE "bookCategories"`);
        await queryRunner.query(`DROP TABLE "authors"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TABLE "coursePurchases"`);
        await queryRunner.query(`DROP TABLE "courseCategories"`);
        await queryRunner.query(`DROP TABLE "courseLikes"`);
        await queryRunner.query(`DROP TABLE "courseReviews"`);
        await queryRunner.query(`DROP TABLE "courseSections"`);
        await queryRunner.query(`DROP TABLE "courseLessons"`);
        await queryRunner.query(`DROP TABLE "usersLessons"`);
        await queryRunner.query(`DROP TABLE "difficulties"`);
        await queryRunner.query(`DROP TABLE "languages"`);
        await queryRunner.query(`DROP TABLE "otpCodes"`);
        await queryRunner.query(`DROP TYPE "public"."otpCodes_type_enum"`);
        await queryRunner.query(`DROP TABLE "reportCategories"`);
    }

}
